#MUSIC AUTOMATION TOOL (MAT) for Europa Universalis 4

#This is a script that creates the required .asset file and a basic .txt file for your Europa Universalis 4 Music Mod based on the .ogg files inside your mod's Music folder.

#The script will skip over any file called "maintheme" as this only replaces the loading music and is not shown in-game by the audio engine.
#The script also allows for your files to be prefixed with a number and an underscore, e.g. 1_Pokemon.ogg, 2_YuGiOh.ogg, so that you can order your music tracks. This naming system is supported up to "99_XXXXX".
#You are strong encouraged to hop into the generated files and check that everything has been created properly. In particular, you may wish to add to the conditions in the .txt file that affect the chances of the music playing.

#This script is open-source and was created by Runite Drill for ease in publishing music mods by community composer Utopia.
#Feel free to join their music modding community and ask any questions: https://discord.gg/SdQhfBM

#For more info/guide on music modding, please visit the EU4 wiki: https://eu4.paradoxwikis.com/Music_modding 

import os

PATH = os.path.abspath(os.path.dirname(__file__))
ALLFILES = os.listdir(PATH)

if os.name == "posix":
  #mac??
  fChar = "/"
else:
  #windows??
  fChar = "\\"

MODTITLE = os.path.dirname(PATH).split(fChar)[-1]

# print(MODTITLE)

musicFiles = []

for file in ALLFILES:
  if file.split(".")[-1] == "ogg":
    name = ".".join(file.split(".")[:-1])
    if name == "maintheme": print("New main theme detected. Will not be written to music mod files.")
    else:
      if name[0].isdigit() and name[1] == "_": name = name[2:]
      elif name[0:1].isdigit() and name[2] == "_": name = name[3:]
      song = {
        "name": name,
        "file": file,
      }
      musicFiles.append(song)

# print(musicFiles)

#create .asset file
with open(PATH + fChar + 'MAT-' + MODTITLE + '-EU4.asset', 'w') as f:
    f.write('#This file was automatically generated by the Music Automation Tool (MAT), created by Runite Drill.\n'+
    '#Consider joining the music modding discord server, Utopia, if you have any questions: https://discord.gg/SdQhfBM.\n\n'+
    '#Please confirm the output is as expected before testing in-game.\n\n')
    for song in musicFiles:
      f.write('music = {\n'+
	    '    name = "'+song["name"]+'"\n'+
	    '    file = "'+song["file"]+'"\n'+
      '}\n')

f.close()

#create .txt file
with open(PATH + fChar + 'MAT-' + MODTITLE + '-EU4.txt', 'w') as f:
    f.write('#This file was automatically generated by the Music Automation Tool (MAT), created by Runite Drill.\n'+
    '#Consider joining the music modding discord server, Utopia, if you have any questions: https://discord.gg/SdQhfBM.\n\n'+
    '#In this file you can specific the triggers and conditions in which the music will play in-game.\n'+
    '#Consult the music modding page on the EU4 wiki for more info: https://eu4.paradoxwikis.com/Music_modding.\n'+
    '#Please confirm the output is as expected before testing in-game.\n\n')
    for song in musicFiles:
      f.write('song = {\n'+
	    '    name = "'+song["name"]+'"\n'+
	    '    chance = {\n'+
      '        modifier = { factor = 1 }\n'+
      '    }\n'+
      '}\n')

f.close()